### ISSUE TITLE
The meter warringstakes faucet link in the documentation is pointing to Meter Wallet https://wallet.meter.io/swap

### ISSUE THREAD

**Issue by lopeselio** [meterio/meter_docs#18]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/43913734/171703690-c7c62ac7-0d12-496b-9713-a664149d0fea.png">

Shouldn't it be linking devs to [https://faucet-warringstakes.meter.io/](https://faucet-warringstakes.meter.io/)

**Comment by xiaohanzhu** [comment]
fixed
